"""add posts and user_posts

Revision ID: 1b8e4f5a9c2d7
Revises: cd9a39641892
Create Date: 2026-09-03 00:00:00.000000
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '1b8e4f5a9c2d7'
down_revision: Union[str, None] = 'cd9a39641892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='唯一编码，如 ceo、se（RuoYi post_code）'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='岗位名称，如“项目经理”（RuoYi post_name）'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='同级排序，越小越靠前（RuoYi post_sort）'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='岗位描述（RuoYi remark）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('user_posts',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户 ID'),
    sa.Column('post_id', sa.BigInteger(), nullable=False, comment='岗位 ID'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.create_index('ix_user_posts_post_id', 'user_posts', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_posts_post_id', table_name='user_posts')
    op.drop_table('user_posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
