"""add_association_table_indexes

Revision ID: 58747c07743a
Revises: c446c5167005
Create Date: 2026-08-08 13:49:16.673165
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '58747c07743a'
down_revision: Union[str, None] = 'c446c5167005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_role_menus_menu_id', 'role_menus', ['menu_id'], unique=False)
    op.create_index('ix_role_permissions_permission_id', 'role_permissions', ['permission_id'], unique=False)
    op.create_index('ix_user_roles_role_id', 'user_roles', ['role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_roles_role_id', table_name='user_roles')
    op.drop_index('ix_role_permissions_permission_id', table_name='role_permissions')
    op.drop_index('ix_role_menus_menu_id', table_name='role_menus')
    # ### end Alembic commands ###
