"""add_missing_indexes

Revision ID: c446c5167005
Revises: e7f8a9b0c1d2
Create Date: 2026-08-08 13:26:32.818365
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'c446c5167005'
down_revision: Union[str, None] = 'e7f8a9b0c1d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_departments_parent_id'), 'departments', ['parent_id'], unique=False)
    op.create_index(op.f('ix_menus_parent_id'), 'menus', ['parent_id'], unique=False)
    op.create_index(op.f('ix_users_department_id'), 'users', ['department_id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_department_id'), table_name='users')
    op.drop_index(op.f('ix_menus_parent_id'), table_name='menus')
    op.drop_index(op.f('ix_departments_parent_id'), table_name='departments')
    # ### end Alembic commands ###
