"""改注释

Revision ID: cd9a39641892
Revises: dbd57cff99c8
Create Date: 2026-08-21 10:51:17.781512
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = 'cd9a39641892'
down_revision: Union[str, None] = 'dbd57cff99c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'code',
               existing_type=mysql.VARCHAR(length=50),
               comment='唯一编码',
               existing_comment='唯一编码，如 tech、market',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'code',
               existing_type=mysql.VARCHAR(length=50),
               comment='唯一编码，如 tech、market',
               existing_comment='唯一编码',
               existing_nullable=False)
    # ### end Alembic commands ###
