"""initial_schema

Revision ID: dbd57cff99c8
Revises: 
Create Date: 2026-08-21 10:43:59.218693
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'dbd57cff99c8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='唯一编码，如 tech、market'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='部门名称，如“技术部”'),
    sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='上级部门 ID（自引用，删父部门后子部门变顶级）'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='同级排序，越小越靠前'),
    sa.Column('description', sa.Text(), nullable=True, comment='部门描述'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_departments_parent_id'), 'departments', ['parent_id'], unique=False)
    op.create_table('menus',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='唯一编码，用于前端路由 name'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='显示名，如“用户管理”'),
    sa.Column('icon', sa.String(length=50), nullable=True, comment='图标（fa-solid:users 等）'),
    sa.Column('path', sa.String(length=100), nullable=True, comment='路由路径，如 /users/index'),
    sa.Column('component', sa.String(length=200), nullable=True, comment='组件路径，如 system/users/index；null=目录菜单'),
    sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='上级菜单 ID（自引用，删父菜单后子菜单变顶级）'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='同级排序，越小越靠前'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['parent_id'], ['menus.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_menus_parent_id'), 'menus', ['parent_id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('code', sa.String(length=100), nullable=False, comment='权限码，如 user:list'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='显示名，如“用户列表”'),
    sa.Column('resource', sa.String(length=50), nullable=False, comment='资源标识，如 user'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='操作标识，如 list/create/update/delete'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='权限描述'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='唯一编码，如 admin、editor、viewer'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='显示名，如“管理员”'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='角色描述'),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='系统角色标记（True=不允许删除和修改 code）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('role_menus',
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色 ID'),
    sa.Column('menu_id', sa.BigInteger(), nullable=False, comment='菜单 ID'),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'menu_id')
    )
    op.create_index('ix_role_menus_menu_id', 'role_menus', ['menu_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色 ID'),
    sa.Column('permission_id', sa.BigInteger(), nullable=False, comment='权限 ID'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_index('ix_role_permissions_permission_id', 'role_permissions', ['permission_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='登录用户名，唯一'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='bcrypt 哈希后的密码，不存明文'),
    sa.Column('display_name', sa.String(length=50), nullable=False, comment='显示名（如：张三）'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用（禁用=不能登录）'),
    sa.Column('department_id', sa.BigInteger(), nullable=True, comment='所属部门 ID（删除部门时置 NULL）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_department_id'), 'users', ['department_id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户 ID'),
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色 ID'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_index('ix_user_roles_role_id', 'user_roles', ['role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_roles_role_id', table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_department_id'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_role_permissions_permission_id', table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index('ix_role_menus_menu_id', table_name='role_menus')
    op.drop_table('role_menus')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_menus_parent_id'), table_name='menus')
    op.drop_table('menus')
    op.drop_index(op.f('ix_departments_parent_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
